[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "colladar"
version = "0.1.0"

[dependencies]
# crates.io
async-std          = { version = "1.7.0", features = ["attributes"] }
isahc              = { version = "0.9.13" }
parity-scale-codec = { version = "1.3.5" }
pretty_env_logger  = { version = "0.4.0" }
# github.com
frame-system         = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git" }
pangolin-runtime     = { version = "1.2.2", git = "https://github.com/darwinia-network/darwinia-common.git", branch = "pangolin" }
sp-core              = { version = "2.0.0", git = "https://github.com/darwinia-network/substrate.git" }
substrate-api-client = { version = "0.4.10-sub2.0.0", git = "https://github.com/scs/substrate-api-client.git" }

[patch."https://github.com/scs/substrate-api-client.git"]
substrate-api-client = { path = "../substrate-api-client" }

[patch.crates-io]
frame-support              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
frame-system               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authority-discovery = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authorship          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-evm                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-im-online           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-session             = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-timestamp           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-api                     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-application-crypto      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-arithmetic              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authority-discovery     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authorship              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-blockchain              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-babe          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-slots         = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-vrf           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-core                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-externalities           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-finality-grandpa        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-inherents               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-io                      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-runtime                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-session                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-staking                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-state-machine           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-storage                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-timestamp               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-transaction-pool        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-trie                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-utils                   = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-version                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-wasm-interface          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
[patch.'https://github.com/darwinia-network/substrate']
frame-support              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
frame-system               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authority-discovery = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-authorship          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-evm                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-im-online           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-session             = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
pallet-timestamp           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-api                     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-application-crypto      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-arithmetic              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authority-discovery     = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-authorship              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-blockchain              = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-babe          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-slots         = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-consensus-vrf           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-core                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-externalities           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-finality-grandpa        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-inherents               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-io                      = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-runtime                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-session                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-staking                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-state-machine           = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-storage                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-timestamp               = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-transaction-pool        = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-trie                    = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-utils                   = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-version                 = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
sp-wasm-interface          = { git = "https://github.com/AsceticBear/substrate.git", branch = "branch-for-dvm" }
