[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "substrater"
version = "0.1.0"

[dependencies]
# crates.io
array-bytes        = { version = "0.1.0", path = "../subalfred/array-bytes" }
async-std          = { version = "1.8.0", features = ["attributes", "unstable"] }
async-trait        = { version = "0.1.42" }
isahc              = { version = "0.9.13" }
parity-scale-codec = { version = "1.3.5", features = ["derive"] }
pretty_env_logger  = { version = "0.4.0" }
serde              = { version = "1.0.118", features = ["derive"] }
serde_json         = { version = "1.0.60" }
subcryptor         = { version = "0.1.0", features = ["codec", "full-crypto"], path = "../subalfred/subcryptor" }
subhasher          = { version = "0.1.0", path = "../subalfred/subhasher" }
submetadatan       = { version = "0.1.0", features = ["codec", "simplify-metadata"], path = "../subalfred/submetadatan" }
subrpcer           = { version = "0.1.0", path = "../subalfred/subrpcer" }
thiserror          = { version = "1.0.22" }
tracing            = { version = "0.1.22" }
tungstenite        = { version = "0.11.1" }
