[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "colladar"
version = "0.1.0"

[dependencies]
# crates.io
anyhow             = { version = "1.0.35" }
array-bytes        = { version = "0.1.0", path = "../subalfred/array-bytes" }
async-std          = { version = "1.8.0", features = ["attributes", "unstable"] }
async-trait        = { version = "0.1.42" }
isahc              = { version = "0.9.13" }
parity-scale-codec = { version = "1.3.5", features = ["derive"] }
pretty_env_logger  = { version = "0.4.0" }
serde              = { version = "1.0.118", features = ["derive"] }
serde_json         = { version = "1.0.60" }
subcryptor         = { version = "0.1.0", features = ["full-crypto"], path = "../subalfred/subcryptor" }
subhasher          = { version = "0.1.0", path = "../subalfred/subhasher" }
subrpcer           = { version = "0.1.0", path = "../subalfred/subrpcer" }
substorager        = { version = "0.1.0", path = "../subalfred/substorager" }
thiserror          = { version = "1.0.22" }
tracing            = { version = "0.1.22" }
tungstenite        = { version = "0.11.1" }
# github.com
frame-metadata = { version = "12.0.0", git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
